doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        dql:
            string_functions:
                TSMATCH: App\Infrastructure\Doctrine\DQL\TsMatchFunction
                TRGM_MATCH: App\Infrastructure\Doctrine\DQL\TrgmMatchFunction
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Identity:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Identity/Entity'
                prefix: 'App\Domain\Identity\Entity'
                alias: Identity
            Customer:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Customer/Entity'
                prefix: 'App\Domain\Customer\Entity'
                alias: Customer
            Project:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Project/Entity'
                prefix: 'App\Domain\Project\Entity'
                alias: Project
            Invoicing:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Invoicing/Entity'
                prefix: 'App\Domain\Invoicing\Entity'
                alias: Invoicing
            TimeTracking:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/TimeTracking/Entity'
                prefix: 'App\Domain\TimeTracking\Entity'
                alias: TimeTracking
            Authorization:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Authorization/Entity'
                prefix: 'App\Domain\Authorization\Entity'
                alias: Authorization
            Notifications:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Notifications/Entity'
                prefix: 'App\Domain\Notifications\Entity'
                alias: Notifications
            System:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/System/Entity'
                prefix: 'App\Domain\System\Entity'
                alias: System
            Logging:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Logging/Entity'
                prefix: 'App\Domain\Logging\Entity'
                alias: Logging

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
