scheb_two_factor:
    totp:
        enabled: true
        issuer: 'WebDream Manager'
        leeway: 1

    email:
        enabled: true
        sender_email: '%env(MAILER_FROM)%'
        sender_name: 'WebDream Manager'
        digits: 6
        template: '@SchebTwoFactor/Authentication/form.html.twig'
        mailer: App\Infrastructure\External\Email\TwoFactorEmailMailer

    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
