twig_component:
    anonymous_template_directory: 'ui/'
    defaults:
        App\UI\Component\Layout\:
            template_directory: 'layout/'
            name_prefix: 'layout'
        App\UI\Component\Identity\: 'components/identity/'
        App\UI\Component\Customer\: 'components/customer/'
        App\UI\Component\Project\: 'components/project/'
        App\UI\Component\Invoicing\: 'components/invoicing/'
        App\UI\Component\TimeTracking\: 'components/time_tracking/'
        App\UI\Component\Admin\: 'components/admin/'
        App\UI\Component\Logging\: 'components/logging/'
